# Generated by Django 5.2.7 on 2026-03-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landingpage",
            name="gallery_button_link",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="info_button_link",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="sitebranding",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="sitefooter",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
