# Generated by Django 6.0.3 on 2026-03-18 01:45

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_productcustomfield_snipcartsettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='product_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
