# Generated by Django 6.0.3 on 2026-03-18 01:58

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_image_product_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcustomfield',
            name='product',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='app.productpage'),
        ),
        migrations.RemoveField(
            model_name='productpage',
            name='inventory',
        ),
        migrations.AddField(
            model_name='productpage',
            name='sku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
