# Generated by Django 6.0.3 on 2026-04-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contactpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Instagram URL'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text='Paste a Google Maps embed URL here.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='twitter_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Twitter/X URL'),
        ),
        migrations.AlterField(
            model_name='galleryeventpage',
            name='video_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='galleryvideopage',
            name='video_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sitefooter',
            name='contact_link',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
