# Generated by Django 6.0.3 on 2026-03-18 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_productcustomfield_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='inventory',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
