# Generated by Django 5.2.7 on 2026-03-18 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_landingpage_gallery_button_link_and_more"),
        ("app", "0005_productpage_inventory"),
    ]

    operations = []
