# Generated by Django 5.2.7 on 2026-03-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_remove_eventpage_ticket_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventtickettype",
            name="tickets_available",
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
