# Generated by Django 5.2.7 on 2026-03-19 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_eventtickettype_tickets_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventpage",
            name="is_quad_cities",
            field=models.BooleanField(default=False),
        ),
    ]
