# Generated by Django 5.2.7 on 2026-03-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_eventpage_is_quad_cities"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventpage",
            old_name="event_location",
            new_name="venue_name",
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="is_quad_cities",
            field=models.BooleanField(
                default=False,
                help_text="Check if this event takes place in the Quad Cities. Leave unchecked for Water Valley.",
            ),
        ),
    ]
