# Generated by Django 6.0.3 on 2026-03-21 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_eventtickettype_id_alter_productcustomfield_id_and_more'),
        ('app', '0011_rename_event_location_eventpage_venue_name_and_more'),
    ]

    operations = [
    ]
