# Generated by Django 6.0.3 on 2026-03-21 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_merge_20260321_1601'),
        ('app', '0012_merge_20260321_1615'),
    ]

    operations = [
    ]
