# Generated by Django 6.0.3 on 2026-03-21 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_aboutpage_donate_alter_eventtickettype_id_and_more'),
        ('app', '0013_merge_20260321_1717'),
    ]

    operations = [
    ]
