# Generated by Django 6.0.4 on 2026-04-22 20:00

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="RocketteAboutPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("hero_title", models.CharField(blank=True, max_length=255)),
                ("intro_text", wagtail.fields.RichTextField(blank=True)),
                (
                    "training_items",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="List of training areas (bulleted list recommended)",
                    ),
                ),
                ("programs_intro", models.CharField(blank=True, max_length=255)),
                ("mentorship_text", wagtail.fields.RichTextField(blank=True)),
                ("creative_arts_text", wagtail.fields.RichTextField(blank=True)),
                ("athletics_text", wagtail.fields.RichTextField(blank=True)),
                ("pwam_text", wagtail.fields.RichTextField(blank=True)),
                (
                    "belief_items",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Short belief statements (bulleted list recommended)",
                    ),
                ),
                ("pwam_quote", wagtail.fields.RichTextField(blank=True)),
                ("pwam_overview", wagtail.fields.RichTextField(blank=True)),
                ("pwam_impact", wagtail.fields.RichTextField(blank=True)),
                ("cta_text", models.CharField(blank=True, max_length=255)),
                (
                    "cta_button_text",
                    models.CharField(default="Contact Us", max_length=50),
                ),
                (
                    "pwam_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
