# Generated by Django 6.0.4 on 2026-04-22 20:29

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_rocketteaboutpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="rocketteaboutpage",
            name="pwam_teach",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
