# Generated by Django 6.0.4 on 2026-04-24 00:35

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_rocketteaboutpage_pwam_teach"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutpage",
            name="community_programs",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="impact_text",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="locations",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="partner_text",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="youth_support",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
